{
  try {
    _doStart();
  }
 catch (  Exception e) {
    _logger.error(e.getMessage(),e);
  }
}
